- name: Apply nginx.conf
  file:
    src: "/home/{{ application_user }}/git/isucon/mysql/conf.d/{{ item }}"
    dest: "/etc/nginx/conf.d/{{ item }}"
    owner: root
    group: root
    state: link
  with_items:
    - gzip.conf
    - log_format.conf

- name: Reload nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes
