- name: 使用言語を変更する
  block:
    - name: stop
      systemd:
        name: "{{ isucon }}.{{ item }}"
        state: stopped
      with_items: "{{ languages.disable }}"

    - name: start
      systemd:
        name: "{{ isucon }}.{{ item }}"
        state: started
      with_items: "{{ languages.enable }}"
