- name: mysql.cnfをデプロイする
  template:
    src: templates/mysql/conf.d/mysql.cnf
    dest: /etc/mysql/conf.d/mysql.cnf
  register: mysql_cnf

- name: configを反映する
  when: mysql_cnf is changed
  block:
    - name: slow.logを作成しておく
      file:
        path: /var/log/mysql/slow.log
        owner: mysql
        group: mysql
        state: touch

    - name: mysqlを再起動する
      systemd:
        name: mysql
        state: restarted

    - name: 現在のslow.logを空にする
      shell: ": > /var/log/mysql/slow.log"
