- hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: apt update/upgrade
      apt:
        update_cache: yes
        cache_valid_time: 86400
        upgrade: yes

    - include_tasks: tasks/pt.yml
    - include_tasks: tasks/alp.yml
    - include_tasks: tasks/redis.yml
