- hosts: common
  remote_user: ubuntu
  become: true

  tasks:
    - name: apt update/upgrade
      apt:
        update_cache: yes
        cache_valid_time: 86400
        upgrade: yes

    - include_tasks: tasks/alp.yml
    - include_tasks: tasks/redis.yml
    - include_tasks: tasks/nginx.yml
    - include_tasks: tasks/pt.yml
    - include_tasks: tasks/mysql.yml
    - include_tasks: tasks/language.yml

- hosts: web
  remote_user: ubuntu
  become: true

  tasks:
    - name: apt update/upgrade
      apt:
        update_cache: yes
        cache_valid_time: 86400
        upgrade: yes

    - include_tasks: tasks/alp.yml
    - include_tasks: tasks/redis.yml
    - include_tasks: tasks/nginx.yml
    - include_tasks: tasks/language.yml

- hosts: db
  remote_user: ubuntu
  become: true

  tasks:
    - name: apt update/upgrade
      apt:
        update_cache: yes
        cache_valid_time: 86400
        upgrade: yes

    - include_tasks: tasks/pt.yml
    - include_tasks: tasks/mysql.yml

- hosts: deploy
  remote_user: ubuntu
  become: true

  tasks:
    - include_tasks: tasks/deploy.yml
